# Generated by Django 2.1.2 on 2018-10-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('availability', models.DateTimeField()),
                ('city', models.CharField(max_length=2)),
                ('fare', models.SmallIntegerField()),
                ('rate', models.SmallIntegerField()),
                ('number_of_adults', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='hotels', to='hotels.Provider'),
        ),
    ]
