# Generated by Django 2.1.2 on 2018-10-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20181011_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'amenity',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='availability',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='amenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='amenities', to='hotels.Hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='amenity',
            unique_together={('hotel', 'name')},
        ),
    ]
