# Generated by Django 2.1.2 on 2018-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20181013_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
